# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_bg_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='faqindexpage',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='personpage',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roompage',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
