# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20160125_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqindexpage',
            name='public',
        ),
        migrations.AddField(
            model_name='faqpage',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
