# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0010_change_on_delete_behaviour'),
        ('home', '0005_auto_20160125_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='feed_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
