# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20160204_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomindexpage',
            old_name='body',
            new_name='intro',
        ),
    ]
