# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 12:27
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20160204_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpagetag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='home.BlogPage'),
        ),
    ]
