# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 05:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20160207_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqpage',
            name='tags',
        ),
    ]
