# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 05:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_faqpage_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqpage',
            name='tags',
        ),
    ]
