# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-24 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0010_change_on_delete_behaviour'),
        ('home', '0024_auto_20160211_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='feed_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
