# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-01 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_advert_feed_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='roompage',
            name='end',
            field=models.DateField(blank=True, null=True, verbose_name=b'To'),
        ),
        migrations.AddField(
            model_name='roompage',
            name='start',
            field=models.DateField(blank=True, null=True, verbose_name=b'From'),
        ),
    ]
